### ISSUE TITLE
Nature of the object of a ChronometricAge

### ISSUE THREAD

**Issue by tucotuco** [tdwg/chrono#20]
In the definition of  chrono:ChronometricAge  "The age of a specimen or related materials that is generated from a dating assay.", the word "related" worries me a lot, particularly when combined with some of the example values "stratigraphically pre-1104" "Double Tuff".  This implies that related means stratigraphically correlated, which extends to pretty much any fossil placed within any chronostratigraphic unit.  This definition allows the term to be used with any dwc:geologicalContext to provide a date range for that geological context, rather than reporting on dates directly derived from samples, which I understand to be the intent of this proposal.  I'd be much happier with either (1) the term being restricted to application to a material sample, with the removal of "related material", or (2) the explicit expansion of the vocabulary to include correlation, with a term that allows the assertion of whether a chronometricAge is derived directly from the material sample, is derived from a material sample in the same continuous section/exposure/core, or whether the age applies by stratigraphic correlation (probably with discussion of how to handle specimens identified to taxa that define biostratigraphic zones), or (3) an explicit statement that related applies only within a single continuous section/exposure/core, and a term that distinguishes between dates obtained from the material sample itself, or from another material sample.

_Originally posted by @chicoreus in https://github.com/tdwg/chrono/issues/15#issuecomment-732234400_

**Comment by tucotuco** [comment]
`As an environmental archaeologist I'd interpret 'related materials' to include the sediment sample which included the macrofossils (insects, seeds, pollen etc). With the exception of bones, recording of the exact material dated is often missing, especially in legacy data, so dates are generally on samples and not specimens in the databases. Whether and how the specimens and the sample are actually correlated is often missing information, and many samples are fuzzily dated relative to archaeological contexts or artefacts. However, suggestion (1) appears to work in this context. From my perspective suggestion (2) sounds useful, but will generally be blank for most of our datasets (unless anyone can fund someone to look it all up!). (3) Probably doesn't work for many archaeological excavations, which can be a mess.

Apologies for butting in here! I'm monitoring this discussion as we are intending to use the extension to feed data from www.sead.se into https://biodiversitydata.se/.`

_Originally posted by @visead in https://github.com/tdwg/chrono/issues/15#issuecomment-732246646_

**Comment by lbrensk** [comment]
> "This implies that related means stratigraphically correlated, which extends to pretty much any fossil placed within any chronostratigraphic unit. This definition allows the term to be used with any dwc:geologicalContext to provide a date range for that geological context, rather than reporting on dates directly derived from samples, which I understand to be the intent of this proposal."

Thank you for your insightful comment. You are correct about all the definition of the term allows, but that was in fact exactly the intent of the extension. I think the root of the issue is that the current definition of chrono:ChronometricAge may be misleading with its use of the phrase “from a dating assay”. In fact, the intent of the ChronometricAge extension is not to only enable reporting of absolute dates from dating assays. The core purpose of the extension is to provide a place where chronometric age information about specimens can be shared with metadata on how this age information is known. How the chronometric age is known can range from information recorded in legacy collections database entries to data from direct dating assays performed on the physical specimen itself or objects/materials found in stratigraphic association with the specimen. Users must assess whether the age information and its reported evidence are trustworthy or not. Having the option for ambiguity built into the extension allows collection managers to report legacy data and allows researchers to search for specimens with dates that need refining with more thorough dating analyses. As a way to clarify the extension’s diverse use cases, we will revise the definition for chrono:ChronometricAge.
 
As far as the concern about the word “related”, we do intend for the extension to be used to report age information derived from relative dating efforts. These assays are always derived from the analysis of material samples, at some level. These samples may not be the specimen itself, and in many cases, these material samples do not (yet) have catalog numbers or URIs. The “Double Tuff” and “Hawk Rim Tuff” examples are from a paleontological use case where the specimen was found between two layers of volcanic ash that were dated using K-Ar methods. This use case is meant to show how the maximum and minimum ages of the specimen were derived by association with two strata themselves dated using separate dating assays, and how the ability of the extension to report a one-to-many relationship with a specimen enables this type of reporting. To illustrate more of the use cases we have gathered in developing this extension, we will be sharing specific examples with filled out values for the terms on the GitHub page.

We thought hard about the suggestion you made to include another term in the vocabulary, as you suggested. Your suggestion was to explicitly expand the vocabulary “to include correlation, with a term that allows the assertion of whether a chronometricAge is derived directly from the material sample, is derived from a material sample in the same continuous section/exposure/core, or whether the age applies by stratigraphic correlation (probably with discussion of how to handle specimens identified to taxa that define biostratigraphic zones)”. We decided that this extra reporting burden was not required. In cases where the material sample ID used in a dating assay is the same as the sample identifier for the specimen record to which it points, it is clear this is direct dating of the specimen. If the material sample identifier points to something else (e.g. an oyster shell) that was directly dated in the same or nearby stratum, that information can be reported. In all cases where the specimen is not directly dated, the outcome is correlational, and the only issue is whether that correlation is more direct or indirect. We believe an additional term will make this more confusing for the data providers and end users. If users require more information about exactly how these ages were derived, referencing items cited in chronometricAgeReferences or notes in chronometricAgeRemarks can help.

**Comment by robgur** [comment]
@chicoreus Does this clarify the scope and meaning of the class and sufficiently address the doubts you expressed.  We also made a small edit to the definition as a separate issue.

**Comment by chicoreus** [comment]
MaterialSample identifiers might be a way out, but I strongly suspect that most of the time when dating is based on correlation, they won't be known at the point of publication of an occurrence record.   

The statement: "We decided that this extra reporting burden was not required. In cases where the material sample ID used in a dating assay is the same as the sample identifier for the specimen record to which it points, it is clear this is direct dating of the specimen."   Is highly unlikely to be true.  The material sample id of a sample sent for destructive sampling for an age determination is very unlikely to be the same material sample id as the material remaining in a collection to voucher an occurrence, even if the material sample sent for destructive sampling is subsampled from a biological specimen, it will be a new material sample with a different fate - and the expectation would be that a collection management system would assign a different and new material sample ID for the subsample sent out for age determination.   Identity of the material sample IDs is highly unlikely, so the assertion that the biological specimen was subsampled for an age determination, rather than sediment attached to the biological specimen, or another specimen from the same section, or another specimen correlated to the same section all still rely on understanding the relationships between the material sample IDs, not on identity of the material sample IDs.  

I still think that a means of explicitly asserting the nature of the relationship between the occurrence and the dated sample is needed, identity/non identity of the material sample ID values does not provide this information.   

Consider a bulk sample (with material sample id) from a section, which has been sieved into fractions (each with a material sample id, each with some derived by preparation technique relationship to the original sample), one of which has had probable wood fragments sorted out (a material sample with id), a subset of which (subsample, with material sample ID) have been sent on loan to another institution for destructive sampling for an age determination, and from another fraction, a mammal tooth has been isolated (another subsample with it's own material sample id) sent to and accessioned into another insitution which has cataloged it and serves up an occurrence record for the taxon, and has assigned its own material sample id to the tooth.   If a means is present to track the relationships of all of these material sample IDs across insitutions, then it is possible to follow the links and determine that the tooth and the destructive sample with the age determination are derived from the same original bulk sample, but an understanding of these relationships are needed to tell the difference between this case and a case where the tooth itself was subsampled (new subsample with its own fate and own material sample id) and the subsample had an age determination, and a case where a sample from a different section had an age determination and the age depends on correlation.   Relationships amongst material sample ID values need to be understood, as the dated material sample id is very unlikely to be identical to the material sample id of remaining voucher material for an occurrence, and a term for asserting the relationship between what was dated and the occurrence is a much simpler, and necessary way to accomplish this.

**Comment by lbrensk** [comment]
Your point that subsamples may have different sample IDs than the object they came from is a good one. We have decided to add a term that we believe addresses the needs that you have pointed out (see https://github.com/tdwg/chrono/issues/24). We recognize that the concept of this new term, materialDatedRelationship, is the same as ResourceRelationship in Darwin Core, and we are trying to mimic the recommended vocabulary pattern in the new term. After discussion with John Wieczorek @tucotuco , we decided that having this term explicitly in the ChronometricAge extension would be an easier solution for users than using ResourceRelationship, which would essentially require an extension to the extension. Please see issue #24 for the details about this proposed new term and give us any feedback.

**Comment by chicoreus** [comment]
@lbrensk #24 looks like a reasonable proposal to address my concerns.

**Comment by tucotuco** [comment]
Concerns addressed as of commit Term changes implemented as of commit 33a132982e5f6d83dd368b822b3766d23ff00a2b..

**Comment by tucotuco** [comment]
Passed public review.

**Comment by tucotuco** [comment]
Ratified! Closing.
