### ISSUE TITLE
What to do with 4 documents in `docs` that do not belong to the website

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/chrono#41]
The `/docs` directory is where the chrono website is served from. It also contains 4 documents that do not seem to belong to the website, but that are "documents":

- [Feature Report - ChronometricAge Extension.pdf](https://github.com/tdwg/chrono/blob/master/docs/Feature%20Report%20-%20ChronometricAge%20Extension.pdf)
- [Feature Report.md](https://github.com/tdwg/chrono/blob/master/docs/Feature%20Report.md)
- [Implementation Experience Report- ChronometricAge Extension.pdf](https://github.com/tdwg/chrono/blob/master/docs/Implementation%20Experience%20Report-%20ChronometricAge%20Extension.pdf)
- [Implementation Experience Report.md](https://github.com/tdwg/chrono/blob/master/docs/Implementation%20Experience%20Report.md)

1. If these should be served from the website, it is better to place them in `docs/assets/documents`
2. If not, they maybe they can go in a `/reports` directory?

**Comment by tucotuco** [comment]
@baskaufs That all sounds very good.  I like the idea of the TAG making that recommendation about the VMS. Should it go for public commentary since the VMS is a standard?

@peterdesmet Let's go with the /reports directory. Are you willing to make those other changes Steve recommended while doing that? If you want me to, let me know and I will do it after the /reports directory is populated with those four docs.

**Comment by baskaufs** [comment]
Yeah, I think it could essentially be managed using the same process as vocabulary changes, but with the TAG standing in the place of the vocabulary Maintenance Group. 

One of the problems with the VMS is that it's scope is restricted to vocabulary standards. That's because the charge of the task group that created it was restricted to that and not to standards in general. I think that the Process doc says something about the Interest Group that charters the Task Group taking responsibility for maintaining the standard after it's adopted, but at this point I don't even remember which group the Vocab TG was under. @tucotuco, do you remember? It may have been the TAG anyway. It would be useful to clear this up because other orphaned standards like the GUID AS are in the same situation. If the TAG continues to be a functioning group, maybe the TAG could just be given that responsibility.

**Comment by tucotuco** [comment]
No, I don't remember under which group that was spawned, but the TAG makes good sense in any case.

**Comment by ben-norton** [comment]
Those documents are critical for extension efforts. I think we should formalize a reports directory for standards.

**Comment by peterdesmet** [comment]
@tucotuco as this is unrelated to the website work, I'll let you make the necessary changes (including moving to `/reports`).

**Comment by tucotuco** [comment]
Accepted.

**Comment by tucotuco** [comment]
Done.
